#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# the "app_lucky_number" route name is not important yet
homepage:
  path: /
  controller: App\Controller\LuckyController::homepage
app_baha:
  path: /baha
  controller: App\Controller\LuckyController::baha
